<?php

namespace ContainerX2JaWD4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinanceApiClientInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Http\FinanceApiClientInterface' shared service.
     *
     * @return \App\Http\FakeYahooFinanceApiClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Http/FinanceApiClientInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Http/FakeYahooFinanceApiClient.php';

        return $container->privates['App\\Http\\FinanceApiClientInterface'] = new \App\Http\FakeYahooFinanceApiClient();
    }
}
