<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2JaWD4\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2JaWD4/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerX2JaWD4.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerX2JaWD4\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerX2JaWD4\App_KernelTestDebugContainer([
    'container.build_hash' => 'X2JaWD4',
    'container.build_id' => 'de67f4b5',
    'container.build_time' => 1640109837,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2JaWD4');
