<?php

namespace ContainerSOiJJDb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRefreshStockProfileCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RefreshStockProfileCommand' shared autowired service.
     *
     * @return \App\Command\RefreshStockProfileCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/RefreshStockProfileCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Http/FinanceApiClientInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Http/YahooFinanceApiClient.php';

        $container->privates['App\\Command\\RefreshStockProfileCommand'] = $instance = new \App\Command\RefreshStockProfileCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), new \App\Http\YahooFinanceApiClient(($container->privates['http_client'] ?? $container->load('getHttpClientService')), $container->getEnv('RAPID_API_KEY')), ($container->services['.container.private.serializer'] ?? $container->load('get_Container_Private_SerializerService')));

        $instance->setName('app:refresh-stock-profile');

        return $instance;
    }
}
