<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTVBv2S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTVBv2S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQTVBv2S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQTVBv2S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQTVBv2S\App_KernelDevDebugContainer([
    'container.build_hash' => 'QTVBv2S',
    'container.build_id' => '219c9576',
    'container.build_time' => 1640109733,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTVBv2S');
