<?php

namespace ContainerQTVBv2S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getYahoofinanceapiclientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'yahoo-finance-api-client' shared autowired service.
     *
     * @return \App\Http\YahooFinanceApiClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Http/FinanceApiClientInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Http/YahooFinanceApiClient.php';

        return $container->services['yahoo-finance-api-client'] = new \App\Http\YahooFinanceApiClient(($container->privates['http_client'] ?? $container->load('getHttpClientService')), $container->getEnv('RAPID_API_KEY'));
    }
}
